source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '< 1.16.0', '!= 1.15.0', '!= 1.15.1'
# Keep ActiveSupport on 6.1.x to avoid cross-version surprises in the CocoaPods toolchain.
gem 'activesupport', '>= 6.1.7.5', '< 7.0'
gem 'xcodeproj', '< 1.26.0'
gem 'concurrent-ruby', '< 1.3.4'

# Ruby 3.4+ moves some stdlib libraries out of the default gem set.
gem 'base64'
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
