# Uncomment the next line to define a global platform for your project
# platform :ios, '17.0'

target 'VoiceAgent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VoiceAgent
  pod 'AgoraRtcEngine_iOS', '4.5.1'
  # Use RTM lite version (RtmKit subspec) to avoid aosl.xcframework conflict with RTC SDK
  pod 'AgoraRtm', '2.2.6', :subspecs => ['RtmKit']
  pod 'SnapKit'
end
